//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtekProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHRECIBOCAJA
    {
        public int id { get; set; }
        public string PREF { get; set; }
        public string CODCLIENTE { get; set; }
        public string NOMBRES { get; set; }
        public string FORMAPAGO { get; set; }
        public string BANCO { get; set; }
        public string NROAUT { get; set; }
        public Nullable<decimal> TOTALDOL { get; set; }
        public string NROTARJCHEQ { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> MONTOAUT { get; set; }
        public Nullable<System.DateTime> FECSISTEM { get; set; }
        public string NROREC { get; set; }
        public string USERGEN { get; set; }
        public Nullable<System.DateTime> FMANUAL { get; set; }
        public string USERMOD { get; set; }
        public string VERIFICADOMANUAL { get; set; }
        public Nullable<decimal> MONTOMANUAL { get; set; }
    }
}
